# Generated by Django 4.2.4 on 2023-10-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_homepage', '0005_rename_content_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comments',
        ),
    ]
