# Generated by Django 4.2.4 on 2023-10-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_homepage', '0007_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
